<?php
/**
 * Welcome to your Angie AMP Project.
 * This file was auto-generated by the AMP Manager.
 * 
 * Dashboard - Environment Diagnostics for local dev
 * Outputs: Angie version, PHP + top extensions, PHP limits, MariaDB info and connection test
*/

// Configuration shown here mirrors docker-compose defaults
// if you customize database credentials edit here:
$db_host = 'db';
$db_port = 3306;
$root_user = 'root';
$root_pass = 'rootpass123';
$app_user = 'ampuser';
$app_pass = 'ampass456';
$app_db   = 'ampdb';

// Angie and PHP
$php_version = phpversion();

// SERVER_SOFTWARE to detect Angie version
if (isset($_SERVER['SERVER_SOFTWARE'])) {
    $serverSoftware = $_SERVER['SERVER_SOFTWARE'];
    $angie_version = "Server software: " . $serverSoftware;

    // Extract Angie version if present
    if (stripos($serverSoftware, 'Angie') !== false) {
        preg_match('/Angie\/([\d\.]+)/i', $serverSoftware, $matches);
        if (!empty($matches[1])) {
            $angie_version .= "\nAngie server version: " . $matches[1];
        } else {
            $angie_version .= "\nAngie server detected, but version not found.";
        }
    } else {
        $angie_version .= "\nNot running on Angie server.";
    }
} else {
    $angie_version = 'SERVER_SOFTWARE variable not available; run: docker compose exec angie angie -v';
}

// Common PHP extensions
$important_ext = [
  'mysqli', 'pdo_mysql', 'json', 'zip', 'curl',
  'mbstring', 'gd', 'intl', 'xml', 'openssl'
];

// PHP limits
$memory_limit = ini_get('memory_limit') ?: 'unknown';
$upload_max_filesize = ini_get('upload_max_filesize') ?: 'unknown';

// MariaDB version check: try user first, then root
$mariadb_version = null;
$mariadb_connect_msg = '';
function try_mariadb_version($host, $port, $user, $pass) {
  $mysqli = @new mysqli($host, $user, $pass, '', $port);
  if ($mysqli && !$mysqli->connect_error) {
    $res = $mysqli->query('SELECT VERSION() AS v');
    if ($res) {
      $row = $res->fetch_assoc();
      $mysqli->close();
      return $row['v'] ?? 'unknown';
    }
    $mysqli->close();
    return 'connected but version query failed';
  }
  return false;
}

$ver = try_mariadb_version($db_host, $db_port, $app_user, $app_pass);
if ($ver !== false) {
  $mariadb_version = $ver;
  $mariadb_connect_msg = "Connected as app user ($app_user)";
} else {
  $ver2 = try_mariadb_version($db_host, $db_port, $root_user, $root_pass);
  if ($ver2 !== false) {
    $mariadb_version = $ver2;
    $mariadb_connect_msg = "Connected as root ($root_user)";
  } else {
    $mariadb_version = 'Not reachable / credentials invalid';
    $mariadb_connect_msg = 'Connection failed with ampuser and root';
  }
}

// Helper emoji status
function status_emoji($ok) { return $ok ? '✅' : '❌'; }
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Docker Stack Dashboard</title>
  <style>
    body {
      font-family: system-ui, sans-serif;
      max-width: 900px;
      margin: 40px auto;
      padding: 0 20px;
      background: #f8f9fa;
      color: #333;
      line-height: 1.6;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 10px;
    }
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.08);
      padding: 24px;
      margin: 24px 0;
    }
    .info-grid {
      display: grid;
      grid-template-columns: 1fr 2fr;
      gap: 16px 24px;
      margin: 16px 0;
    }
    .label {
      font-weight: bold;
      color: #555;
    }
    .value {
      font-family: 'Courier New', monospace;
      background: #f1f3f5;
      padding: 4px 8px;
      border-radius: 4px;
    }
    .success { color: #27ae60; font-weight: bold; }
    .error   { color: #e74c3c; font-weight: bold; }
    footer {
      margin-top: 60px;
      text-align: center;
      color: #777;
      font-size: 0.9em;
    }
  </style>
</head>
<body>

  <h1>Dashboard - <?= $_SERVER['HTTP_HOST'] ?></h1>

  <div class="card">
    <h2>Core Components</h2>
    <div class="info-grid">
      <div class="label">PHP Version</div>
      <div class="value"><?= htmlspecialchars($php_version) ?></div>

      <div class="label">Angie Version</div>
      <div class="value">
        <?= htmlspecialchars(trim($angie_version)) ?>
        <div style="margin-top:8px; display:flex; gap:8px; align-items:center;">
          <code id="angie-cmd" style="background:#eee;padding:6px 8px;border-radius:4px;font-family:monospace;">docker compose exec angie angie -v</code>
          <button onclick="copyToClipboard('#angie-cmd')" style="padding:6px 10px;border-radius:4px;">Copy</button>
        </div>
      </div>


      <div class="label">MariaDB / MySQL Version</div>
      <div class="value">
        <?php if (strpos($mariadb_version, 'Not reachable') === false): ?>
          <span class="success"><?= status_emoji(true) ?> <?= htmlspecialchars($mariadb_version) ?></span>
        <?php else: ?>
          <span class="error"><?= status_emoji(false) ?> <?= htmlspecialchars($mariadb_version) ?></span>
        <?php endif; ?>
      </div>
    </div>
  </div>

  <div class="card">
    <h2>PHP Extensions</h2>
    <div class="info-grid">
      <div class="label">Extension</div>
      <div class="label">Status</div>
      <?php foreach ($important_ext as $ext): ?>
        <div class="label"><?= htmlspecialchars($ext) ?></div>
        <div class="value"><?= status_emoji(extension_loaded($ext)) ?> <?= extension_loaded($ext) ? '<span class="success">enabled</span>' : '<span class="error">disabled</span>' ?></div>
      <?php endforeach; ?>
    </div>
  </div>

  <div class="card">
    <h2>PHP Limits</h2>
    <div class="info-grid">
      <div class="label">memory_limit</div>
      <div class="value"><?= htmlspecialchars($memory_limit) ?></div>
      <div class="label">upload_max_filesize</div>
      <div class="value"><?= htmlspecialchars($upload_max_filesize) ?></div>
    </div>
  </div>

  <div class="card">
    <h2>Credentials & Customization</h2>
    <div class="info-grid">
      <div class="label">DB Host</div>
      <div class="value"><?= htmlspecialchars($db_host) ?>:<?= htmlspecialchars($db_port) ?></div>
      <div class="label">App DB / User</div>
      <div class="value"><?= htmlspecialchars($app_db) ?> — <?= htmlspecialchars($app_user) ?> / <?= htmlspecialchars($app_pass) ?></div>
      <div class="label">Root</div>
      <div class="value"><?= htmlspecialchars($root_user) ?> / <?= htmlspecialchars($root_pass) ?></div>
    </div>
    <p style="margin-top:12px">To change these defaults edit <strong>./config/docker-compose.yml</strong> (env) and <strong>./config/db-init</strong> for init scripts. Restart containers after edits: <code>docker compose up -d</code>.</p>
  </div>

  <div class="card">
    <h2>Connection Test</h2>
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "Trying to connect to {$db_host}:{$db_port} ...<br>";

// If earlier probe found MariaDB reachable, reuse the user that succeeded
if (strpos($mariadb_version, 'Not reachable') === false) {
    $use_user = (strpos($mariadb_connect_msg, 'app user') !== false) ? $app_user : $root_user;
    $use_pass = ($use_user === $app_user) ? $app_pass : $root_pass;

    $conn = @new mysqli($db_host, $use_user, $use_pass, $app_db, $db_port);
    if ($conn && !$conn->connect_error) {
        echo "<span style='color:green'>✅ SUCCESS! Connected to MariaDB as " . htmlspecialchars($use_user) . "</span>";
        echo "<br>Server: " . htmlspecialchars($conn->server_info);
        echo "<br>Database: " . htmlspecialchars($app_db);
        $conn->close();
    } else {
        $err = $conn ? $conn->connect_error : 'mysqli failed to create object';
        echo "<span style='color:red'>❌ Connection failed: " . htmlspecialchars($err) . "</span>";
    }
} else {
    echo "<span style='color:red'>❌ Database not reachable: " . htmlspecialchars($mariadb_connect_msg) . "</span>";
}
?>g(E_ALL)
  </div>

  <div class="card">
    <h2>Quick Commands (run in terminal at D:\amp)</h2>
    <pre>
docker compose ps                  # all services status
docker compose logs db --tail 30   # last MariaDB logs
docker compose exec php php -v     # PHP version inside container
docker compose exec db mariadb -V  # MariaDB version
    </pre>
  </div>

  <footer>
    AMP – Angie + PHP-FPM + MariaDB<br>
    <a href="http://github.com/gigamaster/amp" target="_blank" noopener noreferrer>GitHub Repository</a><br>
    Test page — safe to delete or replace.
  </footer>

<script>
function copyToClipboard(selector){
  try{
    var el = document.querySelector(selector);
    var text = el ? el.innerText : selector;
    if(navigator.clipboard && navigator.clipboard.writeText){
      navigator.clipboard.writeText(text).then(function(){ alert('Copied: ' + text); });
    } else {
      prompt('Copy command', text);
    }
  } catch(e){
    prompt('Copy command', selector);
  }
}
</script>

</body>
</html>
